language: minimal

dist: focal

services:
  - docker

cache:
  directories:
    - $HOME/.m2/repository

env:
  global:
    - DOCKER_IMG="registry.gitlab.com/offa/docker-images/openjdk"
    - DOCKER_TAG="stable"

jobs:
    include:
    - env: JDK=8
    - env: JDK=11
    - env: JDK=12
    - env: JDK=13
    - env: JDK=14


before_install:
  - docker pull ${DOCKER_IMG}-${JDK}-maven:${DOCKER_TAG}

script:
  - docker run -v ${PWD}:/mnt -v ${HOME}:/root -it ${DOCKER_IMG}-${JDK}-maven:${DOCKER_TAG} /bin/bash -c "cd /mnt; script/ci_build.sh"
