name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 12, 13, 14 ]
    name: jdk-${{ matrix.java }}
    steps:
      - uses: actions/checkout@master
      - name: Build with jdk-${{ matrix.java }}
        uses: actions/setup-java@master
        with:
          java-version: ${{ matrix.java }}
      - run: script/ci_build.sh
