name: ci

on: [ push, pull_request ]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17, 21 ]
    name: jdk-${{ matrix.java }}
    steps:
      - name: Build
        uses: offa/maven-action@f7410831c994990b4402c017391edf6da7d2e944
        with:
          java-version: ${{ matrix.java }}
          pmd: true
