name: ci

on: [ push, pull_request ]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17, 21, 25 ]
    name: jdk-${{ matrix.java }}
    steps:
      - name: Build
        uses: offa/maven-action@9f5d347be226bdc684c2a44182fd19b2e8169442
        with:
          java-version: ${{ matrix.java }}
          pmd: true
