name: ci

on: [ push, pull_request ]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17, 21 ]
    name: jdk-${{ matrix.java }}
    steps:
      - name: Build
        uses: offa/maven-action@80a22ce3dde8582e2adefd516a8c341981b0b563
        with:
          java-version: ${{ matrix.java }}
          pmd: true
