name: ci

on: [ push, pull_request ]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21, 25 ]
    name: jdk-${{ matrix.java }}
    steps:
      - name: Build
        uses: offa/maven-action@6ae95407e3764dbe8a6402cc485cb46702320fe0
        with:
          java-version: ${{ matrix.java }}
          pmd: true
