name: ci

on: [ push, pull_request ]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17, 21, 25-ea ]
    name: jdk-${{ matrix.java }}
    steps:
      - name: Build
        uses: offa/maven-action@5416431fe9db78ba30619456a16ee72bd961deb1
        with:
          java-version: ${{ matrix.java }}
          pmd: true
