name: jenkins-security-scan

on:
  push:
    branches:
      - $default-branch
  pull_request:
  schedule:
    - cron: '0 5 * * 3'

jobs:
  jenkins-security-scan:
    uses: jenkins-infra/jenkins-security-scan/.github/workflows/jenkins-security-scan.yaml@main
    name: jenkins-security-scan
    with:
      java-cache: 'maven'
      java-version: 11